services:
  mongodb:
    image: mongo:7.0.2-jammy
    container_name: allaboutyourbirthday-webdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
  web:
    build: .
    environment:
      - NODE_ENV=production
    container_name: allaboutyourbirthday-client
    ports:
      - "80:3000"
    depends_on:
      - mongodb
    profiles:
      - "prod"
  webdev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    container_name: allaboutyourbirthday-client-dev
    ports:
      - "8080:5173"
    volumes:
      - .:/home/node/app
    depends_on:
      - mongodb
    profiles:
      - "dev"